# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\" \n\rPostIdRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"\x1c\n\nTopRequest\x12\x0e\n\x06metric\x18\x01 \x01(\t\"C\n\x11PostStatsResponse\x12\r\n\x05views\x18\x01 \x01(\x05\x12\r\n\x05likes\x18\x02 \x01(\x05\x12\x10\n\x08\x63omments\x18\x03 \x01(\x05\".\n\x0fTimeSeriesEntry\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"7\n\x12TimeSeriesResponse\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.TimeSeriesEntry\"+\n\tPostEntry\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"+\n\tUserEntry\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"-\n\x10TopPostsResponse\x12\x19\n\x05posts\x18\x01 \x03(\x0b\x32\n.PostEntry\"-\n\x10TopUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.UserEntry2\xda\x02\n\x0cStatsService\x12\x32\n\x0cGetPostStats\x12\x0e.PostIdRequest\x1a\x12.PostStatsResponse\x12;\n\x14GetPostViewsOverTime\x12\x0e.PostIdRequest\x1a\x13.TimeSeriesResponse\x12;\n\x14GetPostLikesOverTime\x12\x0e.PostIdRequest\x1a\x13.TimeSeriesResponse\x12>\n\x17GetPostCommentsOverTime\x12\x0e.PostIdRequest\x1a\x13.TimeSeriesResponse\x12-\n\x0bGetTopPosts\x12\x0b.TopRequest\x1a\x11.TopPostsResponse\x12-\n\x0bGetTopUsers\x12\x0b.TopRequest\x1a\x11.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTIDREQUEST']._serialized_start=15
  _globals['_POSTIDREQUEST']._serialized_end=47
  _globals['_TOPREQUEST']._serialized_start=49
  _globals['_TOPREQUEST']._serialized_end=77
  _globals['_POSTSTATSRESPONSE']._serialized_start=79
  _globals['_POSTSTATSRESPONSE']._serialized_end=146
  _globals['_TIMESERIESENTRY']._serialized_start=148
  _globals['_TIMESERIESENTRY']._serialized_end=194
  _globals['_TIMESERIESRESPONSE']._serialized_start=196
  _globals['_TIMESERIESRESPONSE']._serialized_end=251
  _globals['_POSTENTRY']._serialized_start=253
  _globals['_POSTENTRY']._serialized_end=296
  _globals['_USERENTRY']._serialized_start=298
  _globals['_USERENTRY']._serialized_end=341
  _globals['_TOPPOSTSRESPONSE']._serialized_start=343
  _globals['_TOPPOSTSRESPONSE']._serialized_end=388
  _globals['_TOPUSERSRESPONSE']._serialized_start=390
  _globals['_TOPUSERSRESPONSE']._serialized_end=435
  _globals['_STATSSERVICE']._serialized_start=438
  _globals['_STATSSERVICE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
