# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stats_pb2 as stats__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stats_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStats = channel.unary_unary(
                '/StatsService/GetPostStats',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.PostStatsResponse.FromString,
                _registered_method=True)
        self.GetPostViewsOverTime = channel.unary_unary(
                '/StatsService/GetPostViewsOverTime',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.TimeSeriesResponse.FromString,
                _registered_method=True)
        self.GetPostLikesOverTime = channel.unary_unary(
                '/StatsService/GetPostLikesOverTime',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.TimeSeriesResponse.FromString,
                _registered_method=True)
        self.GetPostCommentsOverTime = channel.unary_unary(
                '/StatsService/GetPostCommentsOverTime',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.TimeSeriesResponse.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/StatsService/GetTopPosts',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopPostsResponse.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/StatsService/GetTopUsers',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopUsersResponse.FromString,
                _registered_method=True)


class StatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostViewsOverTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikesOverTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostCommentsOverTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStats,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.PostStatsResponse.SerializeToString,
            ),
            'GetPostViewsOverTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostViewsOverTime,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.TimeSeriesResponse.SerializeToString,
            ),
            'GetPostLikesOverTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikesOverTime,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.TimeSeriesResponse.SerializeToString,
            ),
            'GetPostCommentsOverTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostCommentsOverTime,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.TimeSeriesResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatsService/GetPostStats',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.PostStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostViewsOverTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatsService/GetPostViewsOverTime',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.TimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostLikesOverTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatsService/GetPostLikesOverTime',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.TimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostCommentsOverTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatsService/GetPostCommentsOverTime',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.TimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatsService/GetTopPosts',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatsService/GetTopUsers',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
